/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cloudfs_lock_service_svc.h"
#include "cloudfs_lock_service.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <sys/syscall.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void stop_handler();
void init();
void destroy();

struct data_str
{
        struct svc_req *rqstp;
        SVCXPRT *transp;
};

// key: char *, value: pthread_rwlock_t
hashmap *hash_map;
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_t pthread;
pthread_attr_t attr;
status acquire_result_cache[2][5000];
status release_result_cache[2][5000];

void stop_handler() {
        printf("rpc server will shutdown....\n");
        destroy();
        exit(1);
}

void init() {
        int i,j;

        signal(SIGINT, stop_handler);
        hash_map = hashmapCreate(0); // use default start size
        for (i = 0; i < 2; i++) {
                for (j = 0; j < 5000; j++) {
                        acquire_result_cache[i][j] = UNALLOC;
                        release_result_cache[i][j] = UNALLOC;
                }
        }
}

void destroy() {
        int i;

        for (i = 0; i < hash_map->size; i++) {
                if (hash_map->table[i].flags & ACTIVE) {
                        lock_item *lm = (lock_item *) hash_map->table[i].data;
                        pthread_mutex_destroy(&lm->mutex);
                        pthread_cond_destroy(&lm->cond);
                        free(lm);
                }
        }

        hashmapDelete(hash_map);
}



void *
serv_request(void *data)
{

        long tid;
        tid = syscall(SYS_gettid);

        struct data_str *ptr_data = (struct data_str *) data;
        struct svc_req *rqstp = ptr_data->rqstp;
        register SVCXPRT *transp = ptr_data->transp;

	union {
		lock_params acquire_1_arg;
		lock_params release_1_arg;
	} argument;
	union {
		status acquire_1_res;
		status release_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ACQUIRE:
		_xdr_argument = (xdrproc_t) xdr_lock_params;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))acquire_1_svc;
		break;

	case RELEASE:
		_xdr_argument = (xdrproc_t) xdr_lock_params;
		_xdr_result = (xdrproc_t) xdr_status;
		local = (bool_t (*) (char *, void *,  struct svc_req *))release_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!lockserviceprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	free(data);

	return;
}

static void
lockserviceprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
        struct data_str *data_ptr = (struct data_str*) malloc(sizeof(struct data_str));
        data_ptr->rqstp = rqstp;
        data_ptr->transp = transp;
        pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
        pthread_create(&pthread,&attr,serv_request,(void *)data_ptr);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (LOCKSERVICEPROG, LOCKSERVICEVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, LOCKSERVICEPROG, LOCKSERVICEVERS, lockserviceprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LOCKSERVICEPROG, LOCKSERVICEVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, LOCKSERVICEPROG, LOCKSERVICEVERS, lockserviceprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LOCKSERVICEPROG, LOCKSERVICEVERS, tcp).");
		exit(1);
	}

	init();

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
